packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  es5-ext: false
  esbuild: true

onlyBuiltDependencies:
  - es5-ext
  - esbuild

overrides:
  esbuild: ^0.25.0
  underscore: ^1.13.8
  vite: ^6.4.3
