import crypto from 'crypto';

let publicKey: crypto.KeyObject;
let privateKey: crypto.KeyObject;

export class BlindRsaAuth {
  constructor() {}

  public async init(): Promise<void> {
    const b64Key = process.env.RSA_PRIVATE_KEY_B64;
    
    if (!b64Key) {
      console.error('FATAL: RSA_PRIVATE_KEY_B64 environment variable is missing.');
      console.error('Run `pnpm run generate-key` locally to generate one, and add it to your environment.');
      process.exit(1);
    }

    try {
      const pem = Buffer.from(b64Key, 'base64').toString('utf-8');
      privateKey = crypto.createPrivateKey(pem);
      publicKey = crypto.createPublicKey(privateKey as any);
    } catch (err) {
      console.error('FATAL: Failed to parse RSA_PRIVATE_KEY_B64. Make sure it is a valid base64 encoded PKCS8 PEM key.', err);
      process.exit(1);
    }
  }

  // Export public key params (n, e) as hex strings
  public getPublicKey(): { n: string; e: string } {
    const jwk = publicKey.export({ format: 'jwk' });
    return {
      n: Buffer.from(jwk.n as string, 'base64url').toString('hex'),
      e: Buffer.from(jwk.e as string, 'base64url').toString('hex')
    };
  }

  // 1. Issuance (Server side): Client sends blinded element, server signs it
  public async signBlinded(blindedElementHex: string): Promise<string> {
    const blindedElement = Buffer.from(blindedElementHex, 'hex');
    
    // In Blind RSA, the server signs the blinded message by raising it to the private exponent (d) mod n.
    // RSA_NO_PADDING applies the raw RSA operation (m^d mod n).
    const signature = crypto.privateDecrypt({
      key: privateKey,
      padding: crypto.constants.RSA_NO_PADDING
    }, blindedElement);
    
    return signature.toString('hex');
  }

  // 2. Verification (Server side): Client sends (x, signature). Server verifies it.
  public async verifyToken(xHex: string, signatureHex: string): Promise<boolean> {
    try {
      // x is the token's pseudonym exactly as the client signed it: the client's
      // message is the UTF-8 bytes of this string (secrets.token_hex(32) encoded),
      // NOT its hex-decoded form. Hex-decoding here would verify over the wrong
      // 32 bytes and reject every otherwise-valid token.
      const x = Buffer.from(xHex, 'utf-8');
      const signature = Buffer.from(signatureHex, 'hex');
      
      // We verify the signature against the original secret X using standard PSS verification.
      return crypto.verify(
        'sha256',
        x,
        {
          key: publicKey,
          padding: crypto.constants.RSA_PKCS1_PSS_PADDING,
          saltLength: 32 // Important: must match the 32-byte salt generated by the client
        },
        signature
      );
    } catch {
      return false;
    }
  }
}

export const blindRsaAuth = new BlindRsaAuth();
